apiVersion: v1
kind: Namespace
metadata:
  name: vulnerable-apps
  labels:
    env: test
    security: monitored
---
apiVersion: v1
kind: Namespace
metadata:
  name: security-testing
  labels:
    env: test
    security: monitored
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
