apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - rules-cm.yaml
  - active-response-cm.yaml
  - configmap.yaml
  - rules-sync-job.yaml
  - daemonset.yaml
