apiVersion: v1
kind: ServiceAccount
metadata:
  name: wazuh-agent-sa
  namespace: wazuh
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: wazuh-agent-active-response
  namespace: vulnerable-apps
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wazuh-agent-active-response
  namespace: vulnerable-apps
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: wazuh-agent-active-response
subjects:
  - kind: ServiceAccount
    name: wazuh-agent-sa
    namespace: wazuh
